-- Tabela para solicitações de registo de membros
-- Execute este script no Supabase SQL Editor

create table if not exists public.solicitacoes_registo (
  id bigint generated by default as identity primary key,
  nome varchar not null,
  email varchar not null,
  role varchar not null check (role in ('admin', 'professor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Evita pedidos duplicados por email
create unique index if not exists uq_solicitacoes_registo_email
  on public.solicitacoes_registo (email);

-- Índice para listagens por data (mais recente primeiro)
create index if not exists idx_solicitacoes_registo_created_at
  on public.solicitacoes_registo (created_at desc);

-- Trigger para manter updated_at atualizado
create or replace function public.set_updated_at_solicitacoes_registo()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_solicitacoes_registo_updated_at on public.solicitacoes_registo;
create trigger trg_solicitacoes_registo_updated_at
before update on public.solicitacoes_registo
for each row execute function public.set_updated_at_solicitacoes_registo();

-- RLS (ajuste conforme o teu modelo de autenticação)
alter table public.solicitacoes_registo enable row level security;

-- Como o projeto atual usa anon key sem auth formal por utilizador,
-- estas policies permitem funcionamento do frontend atual.
drop policy if exists "solicitacoes_select_all" on public.solicitacoes_registo;
create policy "solicitacoes_select_all"
on public.solicitacoes_registo
for select
to anon, authenticated
using (true);

drop policy if exists "solicitacoes_insert_all" on public.solicitacoes_registo;
create policy "solicitacoes_insert_all"
on public.solicitacoes_registo
for insert
to anon, authenticated
with check (true);

drop policy if exists "solicitacoes_update_all" on public.solicitacoes_registo;
create policy "solicitacoes_update_all"
on public.solicitacoes_registo
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "solicitacoes_delete_all" on public.solicitacoes_registo;
create policy "solicitacoes_delete_all"
on public.solicitacoes_registo
for delete
to anon, authenticated
using (true);
